### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by johnfelipe** [Code4SA/pmgbilltracker#45]
(virtualenv-pmgbilltracker)notroot@dhcppc4:~/pmgbilltracker/pmgbilltracker$ python runserver_backend.py
	Traceback (most recent call last):
	  File "runserver_backend.py", line 1, in <module>
		from pmg_backend import app as app_backend
	  File "/home/notroot/pmgbilltracker/pmgbilltracker/pmg_backend/__init__.py", line 4, in <module>
		from flask import Flask
	ImportError: No module named flask

How fix it

**Comment by johnfelipe** [comment]
Hi, please tell me correct steps for installation, tnks

**Comment by petrus-jvrensburg** [comment]
Hi Felipe, it looks like some of the requirements are missing. Once you've activated your virtualenv

    source virtualenv-pmgbilltracker/bin/activate

you need to install the requirements:

    sudo pip install -r requirements/local.txt

**Comment by petrus-jvrensburg** [comment]
B.t.w. thanks for having a look at the code. What is the problem that you need to solve?

We wrote it in order to add some views to a really outdated, badly designed website. The site has lots of content on things like parliamentary committee meetings, but it has no way of navigating the dataset to find everything that's related to a particular bill. So that's the only thing that the pmgbilltracker project was built for.

Right now, we're very close to launching a re-design of the site itself, which includes these bill-centric views. So this project will be retired.

**Comment by johnfelipe** [comment]
you have a date for realease?

**Comment by petrus-jvrensburg** [comment]
Yes, we're releasing at the end of this month. The code is at
https://github.com/Code4SA/pmg-cms-2
